In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf
import datetime as dt
from datetime import timedelta

In [2]:
imports = pd.read_excel("C:\\Users\\miche\\OneDrive\\Documenti\\PROJECTS\\crude oil forecasting\\demand factors\\import_export.xls", sheet_name = "Data 1")

In [3]:
ppi = pd.read_csv("C:\\Users\\miche\\OneDrive\\Documenti\\PROJECTS\\crude oil forecasting\\demand factors\\PPI_commodity.csv")

In [4]:
consumption = pd.read_excel("C:\\Users\\miche\\OneDrive\\Documenti\\PROJECTS\\crude oil forecasting\\demand factors\\prod_supplied.xls", sheet_name = "Data 1")

IMPORTS

In [5]:
imports = imports.iloc[:,:5]
imports.drop(imports.columns[1], axis = 1, inplace = True)
imports.drop(imports.columns[2], axis = 1, inplace = True)
imports

,Back to Contents,Unnamed: 2,Unnamed: 4
0,Sourcekey,WCRIMUS2,WCSIMUS2
1,Date,Weekly U.S. Imports of Crude Oil (Thousand Ba...,Weekly U.S. Crude Oil Imports by SPR (Thousan...
2,1982-08-20 00:00:00,NaN,172
3,1982-08-27 00:00:00,NaN,339
4,1982-09-24 00:00:00,NaN,176
...,...,...,...
2246,2025-10-03 00:00:00,6403,0
2247,2025-10-10 00:00:00,5525,0
2248,2025-10-17 00:00:00,5918,0
2249,2025-10-24 00:00:00,5051,0
2250,2025-10-31 00:00:00,5924,0

In [6]:
imports.columns = ['Date', 'Imports_US', 'Imports_SPR']
imports = imports[~imports["Date"].isin(["Sourcekey", "Date"])].copy()
imports["Date"] = pd.to_datetime(imports["Date"])
imports.set_index("Date", inplace = True)
imports

           Imports_US Imports_SPR
Date
1982-08-20        NaN         172
1982-08-27        NaN         339
1982-09-24        NaN         176
1982-10-01        NaN         140
1982-10-08        NaN         120
...               ...         ...
2025-10-03       6403           0
2025-10-10       5525           0
2025-10-17       5918           0
2025-10-24       5051           0
2025-10-31       5924           0

[2249 rows x 2 columns]

In [7]:
imports.fillna(0, inplace= True)
imports

C:\Users\miche\AppData\Local\Temp\ipykernel_40800\4119057306.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  imports.fillna(0, inplace= True)

            Imports_US  Imports_SPR
Date
1982-08-20           0          172
1982-08-27           0          339
1982-09-24           0          176
1982-10-01           0          140
1982-10-08           0          120
...                ...          ...
2025-10-03        6403            0
2025-10-10        5525            0
2025-10-17        5918            0
2025-10-24        5051            0
2025-10-31        5924            0

[2249 rows x 2 columns]

In [8]:
imports_weekly = imports.resample("W").mean()
imports_weekly.fillna(0, inplace = True)

In [9]:
imports_daily = imports.resample("D").mean()
imports_daily.fillna(0, inplace = True)

PRODUCER PURCHASE INDEX

In [10]:
ppi.columns = ["Date", "PPI_commodity"]
ppi["Date"] = pd.to_datetime(ppi["Date"])
ppi.set_index("Date", inplace = True)
ppi

            PPI_commodity
Date
1913-01-01         12.100
1913-01-02         12.000
1913-01-03         12.000
1913-01-04         12.000
1913-01-05         11.900
...                   ...
2025-01-05        258.678
2025-01-06        260.482
2025-01-07        262.363
2025-01-08        262.104
2025-01-09        262.344

[1353 rows x 1 columns]

In [11]:
ppi_weekly = ppi.resample("W").mean()
ppi_weekly.fillna(0, inplace = True)

In [12]:
ppi_daily = ppi.resample("D").mean()
ppi_daily.fillna(0, inplace = True)

CONSUMPTION

In [13]:
consumption = consumption.iloc[:,:2]
consumption.columns = ["Date", "Consumption_US"]

In [14]:
consumption = consumption.iloc[2: , : ]
consumption["Date"] = pd.to_datetime(consumption["Date"])
consumption.set_index("Date", inplace = True)
consumption

           Consumption_US
Date
1990-11-09          16588
1990-11-16          17019
1990-11-23          15686
1990-11-30          17753
1990-12-07          16901
...                   ...
2025-10-03          21990
2025-10-10          19726
2025-10-17          20014
2025-10-24          21281
2025-10-31          20356

[1826 rows x 1 columns]

In [15]:
consumption_monthly = consumption.resample("M").mean()
consumption_monthly.fillna(0, inplace = True)

C:\Users\miche\AppData\Local\Temp\ipykernel_40800\1935938835.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  consumption_monthly = consumption.resample("M").mean()

In [16]:
consumption_daily = consumption.resample("D").mean()
consumption_daily.fillna(0, inplace = True)

C:\Users\miche\AppData\Local\Temp\ipykernel_40800\2787418244.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  consumption_daily.fillna(0, inplace = True)

DAILY DATASET

In [17]:
demand_factors_daily = pd.concat([imports_daily, ppi_daily, consumption_daily], axis = 1)
demand_factors_daily.fillna(0, inplace = True)
demand_factors_daily

            Imports_US  Imports_SPR  PPI_commodity  Consumption_US
Date
1913-01-01         0.0          0.0           12.1             0.0
1913-01-02         0.0          0.0           12.0             0.0
1913-01-03         0.0          0.0           12.0             0.0
1913-01-04         0.0          0.0           12.0             0.0
1913-01-05         0.0          0.0           11.9             0.0
...                ...          ...            ...             ...
2025-10-27         0.0          0.0            0.0             0.0
2025-10-28         0.0          0.0            0.0             0.0
2025-10-29         0.0          0.0            0.0             0.0
2025-10-30         0.0          0.0            0.0             0.0
2025-10-31      5924.0          0.0            0.0         20356.0

[41212 rows x 4 columns]

In [18]:
demand_factors_daily.to_csv("demand_factors_daily.csv")

WEEKLY DATASET

In [19]:
demand_factors_weekly = pd.concat([imports_weekly, ppi_weekly, consumption], axis = 1)
demand_factors_weekly.fillna(0, inplace = True)
demand_factors_weekly

C:\Users\miche\AppData\Local\Temp\ipykernel_40800\3128755448.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  demand_factors_weekly.fillna(0, inplace = True)

            Imports_US  Imports_SPR  PPI_commodity  Consumption_US
Date
1913-01-05         0.0          0.0      12.000000               0
1913-01-12         0.0          0.0      12.042857               0
1913-01-19         0.0          0.0       0.000000               0
1913-01-26         0.0          0.0       0.000000               0
1913-02-02         0.0          0.0       0.000000               0
...                ...          ...            ...             ...
2025-10-19      5918.0          0.0       0.000000               0
2025-10-24         0.0          0.0       0.000000           21281
2025-10-26      5051.0          0.0       0.000000               0
2025-10-31         0.0          0.0       0.000000           20356
2025-11-02      5924.0          0.0       0.000000               0

[7714 rows x 4 columns]

In [20]:
demand_factors_weekly.to_csv("demand_factors_weekly.csv")

MONTHLY DATASET

In [21]:
demand_factors_monthly = pd.concat([imports, ppi, consumption_monthly], axis = 1)
demand_factors_monthly.fillna(0, inplace = True)
demand_factors_monthly

C:\Users\miche\AppData\Local\Temp\ipykernel_40800\4232570589.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  demand_factors_monthly.fillna(0, inplace = True)

            Imports_US  Imports_SPR  PPI_commodity  Consumption_US
Date
1913-01-01         0.0          0.0           12.1             0.0
1913-01-02         0.0          0.0           12.0             0.0
1913-01-03         0.0          0.0           12.0             0.0
1913-01-04         0.0          0.0           12.0             0.0
1913-01-05         0.0          0.0           11.9             0.0
...                ...          ...            ...             ...
2025-10-03      6403.0          0.0            0.0             0.0
2025-10-10      5525.0          0.0            0.0             0.0
2025-10-17      5918.0          0.0            0.0             0.0
2025-10-24      5051.0          0.0            0.0             0.0
2025-10-31      5924.0          0.0            0.0         20673.4

[3889 rows x 4 columns]

In [22]:
demand_factors_monthly.to_csv("demand_factors_monthly.csv")